In [1]:
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [2]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [3]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

In [6]:
net = simpleNet()
net.W

array([[-0.35178891, -0.0794785 ,  1.40671634],
       [-0.1822763 ,  0.58624994, -0.34468339]])

In [7]:
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

In [8]:
print(dW)

[[ 0.10285951  0.2418757  -0.34473521]
 [ 0.15428927  0.36281355 -0.51710281]]
